### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#2]
Is the new system storing nbt data to ALL mobs. e.g. mobs that aren't stacked but would typically be stacked if 4 more spawned using a specific spawn reason. would those mobs that aren't stacked get the nbt data put on them before they are even stacked?

Also with the new Disable ai thing, mobs cant be pushed and also float in the air, is this normal, i've never tested no-ai before.

**Comment by Nathat23** [comment]
When spawned, providing the entity is not blacklisted (because of spawn reason, entity type or world), the entity will be assigned a stack size of 1.

I'm not sure how to improve upon this, since spigot doesn't persist spawn reasons.

**Comment by Nathat23** [comment]
With disabling ai that's how Minecraft defines it. However I don't think it's the desired effect?

**Comment by Nathat23** [comment]
Closing.

**Comment by LogGits** [comment]
@Nathat23 Sorry just to clarify, if my settings are like this:
```yaml
# Names of worlds where there should be no stacking
worlds-blacklist:
  - world
  - world_the_end
  - world_the_nether
worlds-blacklist-invert: true
# Types of entity which should not stack
types-blacklist: 
  - VILLAGER
  - PARROT
  - HORSE
  - MULE
  - CAT
  - WOLF
  - DONKEY
  - LLAMA
  - ZOMBIE_VILLAGER
  - ZOMBIE_HORSE
  - SKELETON_HORSE
  - SNOWMAN
  - TURTLE
  - TRIDENT
types-blacklist-invert: false
# If the entity's spawns reason is listed below, do not stack.
reason-blacklist: 
  - BREEDING
  - SPAWNER
reason-blacklist-invert: true
```
does this mean:
1) entities can only stack in those worlds
2) those entity types will never be stacked
3) if an entity is not blacklisted and spawned via the spawn reasons (Breeding or Spawner) it will;
- have the stack size nbt data added
- be stackable

Is this correct?
