### ISSUE TITLE
Vvisibility "NEARBY" Settings don't works.

### ISSUE THREAD

**Issue by PaDo90** [Nathat23/StackMob-5#226]
Hello, I set up the "NEARBY" option in the display-name section but it don't work for me and my users on the server.
The Tag will only be showing when a player hovers their crosshair on the entity. I already made a reload and a restart from the Server.

```
display-name:
  # The formatting of the name tag which is shown when the stack size is above the threshold.
  # Both legacy and RGB hex color codes are supported, these need to be prefixed by the '&' symbol.
  # Placeholders:
  # %type% - the entity's type
  # %size% - the size of the stack
  format: '&a%type% &d(%size%)'
  # Whether the display tag can only be seen when the player targets the entity.
  # Mode:
  # ALWAYS - The tag will always be visible as long as the entity is loaded.
  # HOVER - The tag will only be visible when the player hovers their crosshair on the entity.
  # NEARBY - The tag will only be visible when the player is in range of the entity. (more resource intensive, requires ProtocolLib on 1.16 servers)
  visibility: NEARBY
  # Options for when 'NEARBY' is used above. (*)
  nearby:
    # The range from which the tag should be visible.
    # Format: [(x cord),(y cord),(z cord)]
    range: [10,10,10]
    # How often (in ticks) the tag visibility status of an entity should be updated. (20 ticks = 1 second)
    interval: 20
  # Don't show the tag if the stack size of this entity if it is equal to or below the value specified.
  threshold: 1
```

**Comment by Nathat23** [comment]
1.17 or 1.16?

**Comment by PaDo90** [comment]
> 1.17 or 1.16?

[23:12:38 INFO]: Server Version: git-Paper-779 (MC: 1.16.5)
[23:12:38 INFO]: NMS: PAPER v1_16_R3
[23:12:38 INFO]: Operating System: Linux
[23:12:38 INFO]: Allocated Memory: 24576Mb
[23:12:38 INFO]: Online Players: 6
[23:12:38 INFO]: TPS from last 1m, 5m, 15m: 20, 20, 20

StackMob Version 5.6.2

**Comment by Nathat23** [comment]
Do you have the ProtocolLib plugin?

**Comment by PaDo90** [comment]
> Do you have the ProtocolLib plugin?

Yes

```
[23:19:13 INFO]: ProtocolLib v4.6.1-SNAPSHOT-b505
[23:19:13 INFO]: Authors: dmulloy2 and Comphenix
[23:19:13 INFO]: Issues: https://github.com/dmulloy2/ProtocolLib/issues
```

**Comment by Nathat23** [comment]
Download build from https://ci.codemc.io/job/Nathat23/job/StackMob-5/ and that may fix it.

**Comment by PaDo90** [comment]
> Download build from https://ci.codemc.io/job/Nathat23/job/StackMob-5/ and that may fix it.

Thank you, I have tried. But it is still not a solution. Players need to be 2 blocks near the mob and hovers their crosshair on the entity. to see the name. I set up 10x10x10 Blocks.

```
  visibility: NEARBY
  # Options for when 'NEARBY' is used above. (*)
  nearby:
    # The range from which the tag should be visible.
    # Format: [(x cord),(y cord),(z cord)]
    range: [10,10,10]
```
