### ISSUE TITLE
Name mode PREVENT, prevents name tagging any mobs.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#261]
Paper 1.19.2 Build 142
StackMob-5 built upon: https://github.com/Nathat23/StackMob-5/commit/e5b74af5308928a8135ff1d97d4dc6bf1d236b66 (latest)

```
events:
  # When a nametag is used to rename a mob (see nametag)
  nametag:
    enabled: true
    # SLICE - slice off an entity so that a single entity is named and becomes unstackable
    # PREVENT - prevent nametags from working with stacked mobs
    mode: PREVENT
```

The above config prevents naming absolutely any mobs, not just stacked, as the commented section of the configuration states.
Spawn just one mob, try to name tag, no bueno.

Changing to SLICE fixes this.
