### ISSUE TITLE
No money from breeding cows and pigs using Jobs

### ISSUE THREAD

**Issue by Bloodlex** [Nathat23/StackMob-5#265]
Hey,

I use Jobs and StackMob. I have job integration turned on. I don't get money from breeding cows and pigs 🙁. Could you please check that?

StackMob config: [https://pastebin.com/UtfLq1gy](https://pastebin.com/UtfLq1gy).

Jobs Farmer config:

```
    Cow:
      income: 4.0
      points: 4.0
      experience: 5.0
    Pig:
      income: 4.0
      points: 4.0
      experience: 5.0
```
Server version: **Purpur-1835 (MC: 1.19.2)**
StackMob: **5.8.4**
Jobs: **5.1.0.1**
