### ISSUE TITLE
Weird stuff happens when merging three or more entities at once, or one of the stacks has a size of 1

### ISSUE THREAD

**Issue by Nathat23** [Nathat23/StackMob-5#30]
The behaviour continues to be extremely weird.

- As soon as there are 3 in a stack, the remaining act very random.
- The most I've seen is a stacked 3 plus 3 singles.
- Afterwards they start disappearing, sometimes, one makes a 4 stack, and the rest continue to disappear.
- Sometimes one makes a 2 stack and instantly disappears, while the main stack continues to remain at 4.

Make yourself the following setup:
https://i.imgur.com/NJF8RIj.png

Right spawner: pig
Left spawner: zombie

And observe with following setup:

Build 10: https://ci.ecocitycraft.com/job/StackMob-5/changes
Config:

```
# If specific entities should have a waiting time before their first stack.
# Designed for monster grinders etc.
wait-to-stack:
  enabled: true
  # For (x) times the stack task fires after spawn, don't stack this entity.
  wait-time: 5
  # Entity types that this should work for.
  types-whitelist:
    - ZOMBIE
    - SKELETON
    - PIG_ZOMBIE
    - CREEPER
    - ENDERMAN
  types-whitelist-invert: false
  # Spawn reasons that this should work for.
  reasons-whitelist:
    - SPAWNER
  reasons-whitelist-invert: false
```

As always, wait-to-stack.enabled set to false fixes **ALL** issues.

_Originally posted by @andrewkm in https://github.com/Nathat23/StackMob-5/issues/23#issuecomment-575988725_
