### ISSUE TITLE
Old SMv4 non stackable mobs are getting stacked

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#32]
Using this:
```yaml
# Names of worlds where there should be no stacking
worlds-blacklist:
  - world
  - world_the_end
  - world_the_nether
worlds-blacklist-invert: true
# Types of entity which should not stack
types-blacklist: 
  - VILLAGER
  - PARROT
  - HORSE
  - MULE
  - CAT
  - WOLF
  - DONKEY
  - LLAMA
  - ZOMBIE_VILLAGER
  - ZOMBIE_HORSE
  - SKELETON_HORSE
  - SNOWMAN
  - TURTLE
  - TRIDENT
types-blacklist-invert: false
# If the entity's spawns reason is listed below, do not stack.
reason-blacklist: 
  - BREEDING
  - SPAWNER
reason-blacklist-invert: true
```
It appears that placed fish using a bucket before the 5.0 update, are now being stacked. Is there a way I can just remove old stacked items instead of converting them?

**Comment by Nathat23** [comment]
So were the fish supposed to be stacked before the update or not?

**Comment by LogGits** [comment]
They where blocked from stacking, ill send u my old v4 config when i get home

**Comment by LogGits** [comment]
These were the values in my v4 config:
```yaml
stack-reasons:
    - BREEDING
    - SPAWNER
no-stack-types:
    - VILLAGER
    - PARROT
    - HORSE
    - MULE
    - CAT
    - WOLF
    - DONKEY
    - LLAMA
    - ZOMBIE_VILLAGER
    - ZOMBIE_HORSE
    - SKELETON_HORSE
    - SNOWMAN
    - TURTLE
    - TRIDENT
```
